# Extra-DamageIndicator v1.2.0
# Set which type of mobs has enabled/disabled holograms.
types:
  Mob: true
  Animals: true
  Players: true
# How long hologram stay in the world in seconds. (MUST BE INTEGER!)
cooldown: 1
# All plugins that are supported by Extra-DamageIndicator
hooks:
  HolographicDisplays: false
  DecentHolograms: false
# If you want display hologram while player is sneaking, set this option to true, otherwise set this to false.
sneaking: true
# Y-CORDINATION / IF YOU USE HOLOGRAPHIC-DISPLAYS PLUGIN IN THE CASE OF A PLAYER RECOMMENDED IS 3/
# ALSO IF YOU DON'T USE HOLOGRAPHIC-DISPLAYS PLUGIN RECOMMENDED FOR PLAYERS IS 2/1
add-y-coord: 1
# Messages
Damage-Message: "&c-&a%damage%"
Regeneration-Message: "&a+&7[&c%health%&7]"