main: me.dreamdevs.github.edi.EDIMain
name: ${project.artifactId}
version: ${project.version}
author: DreamDevs
api-version: 1.13

commands:
  extradamageindicator:
    aliases: [extradi, edamageindicator, edi, edindicator, damageindicator]
    permission: edi.command
    permission-message: You do not have permission to use this command!