main: me.MrABCDevelopment.main.EDMMain
name: Extra-DamageIndicator
version: 1.1.0
Author: MrABCDevelopment
softdepend: [HolographicDisplays]

commands:
  EdiReload:
    permission: EDI.reload
    permission-message: You do not have permission to use this command!

