main: me.mrabcdevelopment.github.edi.EDIMain
name: Extra-DamageIndicator
version: 1.2.1
Author: MrABCDevelopment
softdepend: [HolographicDisplays, DecentHolograms]

commands:
  extradamageindicator:
    aliases: [extradi, edamageindicator, edi, edindicator, damageindicator]
    permission: edi.command
    permission-message: You do not have permission to use this command!