#TYPES MOBS
types:
  Mob: true
  Animals: true
  Players: true
#COOLDOWN IN SECONDS
cooldown: 1
#MESSAGE
message: "&c-&a%EDAMAGE%"
#Y-CORDINATION / IF YOU USE HOLOGRAPHIC-DISPLAYS PLUGIN IN THE CASE OF A PLAYER RECOMMENDED IS 3/
#ALSO IF YOU DON'T USE HOLOGRAPHIC-DISPLAYS PLUGIN RECOMMENDED FOR PLAYERS IS 2/1
y: 1