main: me.dreamdevs.github.edi.EDIMain
name: Extra-DamageIndicator
version: 1.4.1
author: DreamDevs
api-version: 1.13

commands:
  extradamageindicator:
    aliases: [extradi, edamageindicator, edi, edindicator, damageindicator]
    permission: edi.command
    permission-message: You do not have permission to use this command!