main: me.dreamdevs.github.edi.EDIMain
name: Extra-DamageIndicator
version: 1.3.2
Author: DreamDevs
softdepend: [HolographicDisplays, DecentHolograms]

commands:
  extradamageindicator:
    aliases: [extradi, edamageindicator, edi, edindicator, damageindicator]
    permission: edi.command
    permission-message: You do not have permission to use this command!